In [1]:
from SLIM_BPR.Cython.SLIM_BPR_Cython import SLIM_BPR_Cython
from SLIM_ElasticNet.SLIMElasticNetRecommender import SLIMElasticNetRecommender

from MatrixFactorization.Cython.MatrixFactorization_Cython import MatrixFactorization_BPR_Cython, MatrixFactorization_FunkSVD_Cython
from MatrixFactorization.PureSVD import PureSVDRecommender

from Base.NonPersonalizedRecommender import TopPop, Random

from KNN.UserKNNCFRecommender import UserKNNCFRecommender
from KNN.ItemKNNCFRecommender import ItemKNNCFRecommender
from KNN.ItemKNNCBFRecommender import ItemKNNCBFRecommender

from KNN.ItemKNNScoresHybridRecommender import ItemKNNScoresHybridRecommender
from KNN.ItemKNNScoresHybridRecommender3 import ItemKNNScoresHybridRecommender3

from KNN.ItemKNNSimilarityHybridRecommender import ItemKNNSimilarityHybridRecommender
from KNN.ItemKNNSimilarityHybridRecommender3 import ItemKNNSimilarityHybridRecommender3
from KNN.ItemKNNSimilarityHybridRecommender4 import ItemKNNSimilarityHybridRecommender4

from KNN.UserKNNCBFRecommender import UserKNNCBFRecommender


#from GraphBased.RP3betaRecommender import RP3betaRecommender
#from GraphBased.P3alphaRecommender import P3alphaRecommender

In [2]:
import traceback, os
import scipy.sparse
import pandas as pd
import numpy as np

URM_all = scipy.sparse.load_npz('./Matrix/URM_all_matrix.npz')
ICM_all = scipy.sparse.load_npz('./Matrix/ICM_all_matrix.npz')
URM_train = scipy.sparse.load_npz('./Matrix/URM_train_matrix.npz')
URM_test = scipy.sparse.load_npz('./Matrix/URM_test_matrix.npz')



#Load playlistsIDS
train_df= pd.read_csv('all/train.csv',low_memory = False)
all_userID=train_df.playlist_id.unique()

In [8]:
import implicit

# initialize a model
model = implicit.als.AlternatingLeastSquares(factors=200, regularization=0.1,iterations=5)

# train the model on a sparse matrix of item/user/confidence weights
item_user_data=URM_train.T
print("ITEM USER ={}".format(item_user_data.shape))
model.fit(item_user_data)

# recommend items for a user
user_items = item_user_data.T.tocsr()
print("USER ITEM ={}".format(user_items.shape))


#uno per volta predico tutti gli utenti e estraggo dalla lista delle 10 predizioni, dalla tupla, la track
rec_matrix=np.zeros((50446,10))

for u in all_userID:
    rec = model.recommend(u, user_items)
    for x in range (10):
        rec_matrix[u,x]=rec[x][0]
print(rec_matrix)   

ITEM USER =(20635, 50446)


100%|██████████| 5.0/5 [00:04<00:00,  1.34it/s]


USER ITEM =(50446, 20635)
[[15187. 13250.  7545. ... 20152. 12768.  4202.]
 [ 2336.  4202.  7077. ...  5534.  1422.  8195.]
 [ 3855.  4916.  5817. ...  7611.  3880. 18490.]
 ...
 [15542.   229.  7465. ...  6491.  2627. 18059.]
 [11638.  4106.  7153. ... 17780. 19991. 14591.]
 [ 7889.  2627.   648. ...  5097. 16494.  8866.]]


In [4]:
import numpy as np
import scipy.sparse as sps



def precision(is_relevant, relevant_items):

    #is_relevant = np.in1d(recommended_items, relevant_items, assume_unique=True)

    precision_score = np.sum(is_relevant, dtype=np.float32) / len(is_relevant)

    return precision_score



def recall(is_relevant, relevant_items):

    #is_relevant = np.in1d(recommended_items, relevant_items, assume_unique=True)

    recall_score = np.sum(is_relevant, dtype=np.float32) / relevant_items.shape[0]

    return recall_score



def MAP(is_relevant, relevant_items):

    #is_relevant = np.in1d(recommended_items, relevant_items, assume_unique=True)

    # Cumulative sum: precision at 1, at 2, at 3 ...
    p_at_k = is_relevant * np.cumsum(is_relevant, dtype=np.float32) / (1 + np.arange(is_relevant.shape[0]))

    map_score = np.sum(p_at_k) / np.min([relevant_items.shape[0], is_relevant.shape[0]])

    return map_score

In [5]:
def evaluate_algorithm(URM_test, recMatrix, at=10):

    cumulative_precision = 0.0
    cumulative_recall = 0.0
    cumulative_MAP = 0.0

    num_eval = 0

    URM_test = sps.csr_matrix(URM_test)

    n_users = URM_test.shape[0]


    for user_id in range(n_users):

        if user_id % 10000 == 0:
            print("Evaluated user {} of {}".format(user_id, n_users))

        start_pos = URM_test.indptr[user_id]
        end_pos = URM_test.indptr[user_id+1]

        if end_pos-start_pos>0:

            relevant_items = URM_test.indices[start_pos:end_pos]

            recommended_items = recMatrix[user_id]
            num_eval+=1

            is_relevant = np.in1d(recommended_items, relevant_items, assume_unique=True)

            cumulative_precision += precision(is_relevant, relevant_items)
            cumulative_recall += recall(is_relevant, relevant_items)
            cumulative_MAP += MAP(is_relevant, relevant_items)


    cumulative_precision /= num_eval
    cumulative_recall /= num_eval
    cumulative_MAP /= num_eval

    print("Recommender performance is: Precision = {:.4f}, Recall = {:.4f}, MAP = {:.4f}".format(
        cumulative_precision, cumulative_recall, cumulative_MAP))

    result_dict = {
        "precision": cumulative_precision,
        "recall": cumulative_recall,
        "MAP": cumulative_MAP,
    }

    return result_dict

In [6]:
evaluate_algorithm(URM_test,rec_matrix)

Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0105, Recall = 0.0205, MAP = 0.0037


{'MAP': 0.003655664736114788,
 'precision': 0.01053121124431573,
 'recall': 0.020542532529209664}

In [7]:
import implicit

factors=[10,50,100,200,500]
reg=[0.01, 0.001,0.1,0.0001]
it=[5,20,40]
item_user_data=URM_train.T
user_items = item_user_data.T.tocsr()





for f in factors:
    for r in reg:
        for i in it:
            print("fator={}, regularization={}, iterations={}".format(f,r,i))
            # initialize a model
            model = implicit.als.AlternatingLeastSquares(factors=f, regularization=r,iterations=i)

            # train the model on a sparse matrix of item/user/confidence weights
            #print("ITEM USER ={}".format(item_user_data.shape))
            model.fit(item_user_data)

            # recommend items for a user
            #print("USER ITEM ={}".format(user_items.shape))


            #uno per volta predico tutti gli utenti e estraggo dalla lista delle 10 predizioni, dalla tupla, la track
            rec_matrix=np.zeros((50446,10))

            for u in all_userID:
                rec = model.recommend(u, user_items)
                for x in range (10):
                    rec_matrix[u,x]=rec[x][0]
            #print(rec_matrix)   
            evaluate_algorithm(URM_test,rec_matrix)

  0%|          | 0/5 [00:00<?, ?it/s]

fator=10, regularization=0.01, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  3.19it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0301, Recall = 0.0600, MAP = 0.0238
fator=10, regularization=0.01, iterations=20


100%|██████████| 20.0/20 [00:05<00:00,  3.80it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  1%|▏         | 0.5/40 [00:00<00:09,  4.20it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0297, Recall = 0.0586, MAP = 0.0234
fator=10, regularization=0.01, iterations=40


100%|██████████| 40.0/40 [00:15<00:00,  2.48it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


 10%|█         | 0.5/5 [00:00<00:01,  4.05it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0279, Recall = 0.0541, MAP = 0.0219
fator=10, regularization=0.001, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  2.91it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0314, Recall = 0.0631, MAP = 0.0256
fator=10, regularization=0.001, iterations=20


100%|██████████| 20.0/20 [00:05<00:00,  3.31it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  1%|▏         | 0.5/40 [00:00<00:10,  3.68it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0285, Recall = 0.0552, MAP = 0.0223
fator=10, regularization=0.001, iterations=40


100%|██████████| 40.0/40 [00:11<00:00,  2.90it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/5 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0284, Recall = 0.0552, MAP = 0.0222
fator=10, regularization=0.1, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  3.24it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  2%|▎         | 0.5/20 [00:00<00:04,  4.54it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0310, Recall = 0.0613, MAP = 0.0245
fator=10, regularization=0.1, iterations=20


100%|██████████| 20.0/20 [00:05<00:00,  3.28it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/40 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0295, Recall = 0.0581, MAP = 0.0233
fator=10, regularization=0.1, iterations=40


100%|██████████| 40.0/40 [00:10<00:00,  4.38it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/5 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0289, Recall = 0.0565, MAP = 0.0224
fator=10, regularization=0.0001, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  3.47it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  2%|▎         | 0.5/20 [00:00<00:04,  4.58it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0305, Recall = 0.0597, MAP = 0.0238
fator=10, regularization=0.0001, iterations=20


100%|██████████| 20.0/20 [00:06<00:00,  2.74it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  1%|▏         | 0.5/40 [00:00<00:08,  4.54it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0288, Recall = 0.0564, MAP = 0.0230
fator=10, regularization=0.0001, iterations=40


100%|██████████| 40.0/40 [00:10<00:00,  4.15it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/5 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0290, Recall = 0.0567, MAP = 0.0228
fator=50, regularization=0.01, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  2.79it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/20 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0492, Recall = 0.1023, MAP = 0.0452
fator=50, regularization=0.01, iterations=20


100%|██████████| 20.0/20 [00:07<00:00,  2.79it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/40 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0489, Recall = 0.1015, MAP = 0.0437
fator=50, regularization=0.01, iterations=40


100%|██████████| 40.0/40 [00:13<00:00,  2.95it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0183, Recall = 0.0391, MAP = 0.0088
fator=50, regularization=0.001, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  2.93it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0087, Recall = 0.0180, MAP = 0.0034
fator=50, regularization=0.001, iterations=20


100%|██████████| 20.0/20 [00:06<00:00,  2.85it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/40 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0490, Recall = 0.1013, MAP = 0.0444
fator=50, regularization=0.001, iterations=40


100%|██████████| 40.0/40 [00:14<00:00,  2.82it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/5 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0494, Recall = 0.1026, MAP = 0.0440
fator=50, regularization=0.1, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  3.24it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0499, Recall = 0.1031, MAP = 0.0450
fator=50, regularization=0.1, iterations=20


100%|██████████| 20.0/20 [00:07<00:00,  3.20it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446


  0%|          | 0/40 [00:00<?, ?it/s]

Recommender performance is: Precision = 0.0496, Recall = 0.1025, MAP = 0.0446
fator=50, regularization=0.1, iterations=40


100%|██████████| 40.0/40 [00:14<00:00,  2.29it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446


  0%|          | 0/5 [00:00<?, ?it/s]

Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=50, regularization=0.0001, iterations=5


100%|██████████| 5.0/5 [00:01<00:00,  2.94it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/20 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0502, Recall = 0.1038, MAP = 0.0446
fator=50, regularization=0.0001, iterations=20


100%|██████████| 20.0/20 [00:07<00:00,  2.22it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/40 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=50, regularization=0.0001, iterations=40


100%|██████████| 40.0/40 [00:14<00:00,  2.65it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=100, regularization=0.01, iterations=5


100%|██████████| 5.0/5 [00:02<00:00,  1.93it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/20 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0525, Recall = 0.1119, MAP = 0.0474
fator=100, regularization=0.01, iterations=20


100%|██████████| 20.0/20 [00:09<00:00,  2.13it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/40 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0527, Recall = 0.1125, MAP = 0.0484
fator=100, regularization=0.01, iterations=40


100%|██████████| 40.0/40 [00:18<00:00,  2.38it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/5 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0534, Recall = 0.1149, MAP = 0.0484
fator=100, regularization=0.001, iterations=5


100%|██████████| 5.0/5 [00:02<00:00,  2.22it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0535, Recall = 0.1144, MAP = 0.0497
fator=100, regularization=0.001, iterations=20


100%|██████████| 20.0/20 [00:10<00:00,  2.00it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0527, Recall = 0.1118, MAP = 0.0484
fator=100, regularization=0.001, iterations=40


100%|██████████| 40.0/40 [00:19<00:00,  2.22it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446


  0%|          | 0/5 [00:00<?, ?it/s]

Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0529, Recall = 0.1131, MAP = 0.0488
fator=100, regularization=0.1, iterations=5


100%|██████████| 5.0/5 [00:02<00:00,  2.37it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0538, Recall = 0.1142, MAP = 0.0498
fator=100, regularization=0.1, iterations=20


100%|██████████| 20.0/20 [00:08<00:00,  2.56it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0541, Recall = 0.1148, MAP = 0.0494
fator=100, regularization=0.1, iterations=40


100%|██████████| 40.0/40 [00:16<00:00,  2.50it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0529, Recall = 0.1124, MAP = 0.0485
fator=100, regularization=0.0001, iterations=5


100%|██████████| 5.0/5 [00:02<00:00,  2.45it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0536, Recall = 0.1140, MAP = 0.0501
fator=100, regularization=0.0001, iterations=20


100%|██████████| 20.0/20 [00:08<00:00,  2.40it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0531, Recall = 0.1136, MAP = 0.0488
fator=100, regularization=0.0001, iterations=40


100%|██████████| 40.0/40 [00:16<00:00,  2.28it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0531, Recall = 0.1133, MAP = 0.0490
fator=200, regularization=0.01, iterations=5


100%|██████████| 5.0/5 [00:03<00:00,  1.41it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0544, Recall = 0.1185, MAP = 0.0527
fator=200, regularization=0.01, iterations=20


100%|██████████| 20.0/20 [00:14<00:00,  1.43it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0129, Recall = 0.0307, MAP = 0.0071
fator=200, regularization=0.01, iterations=40


100%|██████████| 40.0/40 [00:28<00:00,  1.44it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0006, Recall = 0.0011, MAP = 0.0002
fator=200, regularization=0.001, iterations=5


100%|██████████| 5.0/5 [00:03<00:00,  1.48it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0562, Recall = 0.1231, MAP = 0.0536
fator=200, regularization=0.001, iterations=20


100%|██████████| 20.0/20 [00:14<00:00,  1.36it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=200, regularization=0.001, iterations=40


100%|██████████| 40.0/40 [00:32<00:00,  1.13it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=200, regularization=0.1, iterations=5


100%|██████████| 5.0/5 [00:03<00:00,  1.43it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0548, Recall = 0.1197, MAP = 0.0539
fator=200, regularization=0.1, iterations=20


100%|██████████| 20.0/20 [00:14<00:00,  1.39it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0542, Recall = 0.1184, MAP = 0.0515
fator=200, regularization=0.1, iterations=40


100%|██████████| 40.0/40 [00:30<00:00,  1.27it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=200, regularization=0.0001, iterations=5


100%|██████████| 5.0/5 [00:03<00:00,  1.42it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0548, Recall = 0.1204, MAP = 0.0539
fator=200, regularization=0.0001, iterations=20


100%|██████████| 20.0/20 [00:14<00:00,  1.42it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0006, Recall = 0.0013, MAP = 0.0004
fator=200, regularization=0.0001, iterations=40


100%|██████████| 40.0/40 [00:31<00:00,  1.25it/s]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=500, regularization=0.01, iterations=5


100%|██████████| 5.0/5 [00:13<00:00,  2.66s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0013, Recall = 0.0026, MAP = 0.0009
fator=500, regularization=0.01, iterations=20


100%|██████████| 20.0/20 [00:55<00:00,  2.74s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=500, regularization=0.01, iterations=40


100%|██████████| 40.0/40 [01:51<00:00,  2.87s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=500, regularization=0.001, iterations=5


100%|██████████| 5.0/5 [00:13<00:00,  2.63s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0004, Recall = 0.0009, MAP = 0.0004
fator=500, regularization=0.001, iterations=20


100%|██████████| 20.0/20 [00:56<00:00,  2.75s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=500, regularization=0.001, iterations=40


100%|██████████| 40.0/40 [01:52<00:00,  2.78s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=500, regularization=0.1, iterations=5


100%|██████████| 5.0/5 [00:13<00:00,  2.63s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0035, Recall = 0.0071, MAP = 0.0017
fator=500, regularization=0.1, iterations=20


100%|██████████| 20.0/20 [00:54<00:00,  2.64s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0006, Recall = 0.0012, MAP = 0.0004
fator=500, regularization=0.1, iterations=40


100%|██████████| 40.0/40 [01:54<00:00,  2.76s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
fator=500, regularization=0.0001, iterations=5


100%|██████████| 5.0/5 [00:13<00:00,  2.65s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0003, Recall = 0.0006, MAP = 0.0001
fator=500, regularization=0.0001, iterations=20


100%|██████████| 20.0/20 [00:55<00:00,  2.66s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0004, Recall = 0.0006, MAP = 0.0001
fator=500, regularization=0.0001, iterations=40


100%|██████████| 40.0/40 [01:53<00:00,  2.77s/it]


Evaluated user 0 of 50446
Evaluated user 10000 of 50446
Evaluated user 20000 of 50446
Evaluated user 30000 of 50446
Evaluated user 40000 of 50446
Evaluated user 50000 of 50446
Recommender performance is: Precision = 0.0002, Recall = 0.0003, MAP = 0.0002
